name: CI

on:
    pull_request: 
        branches: 
            - "*"

jobs:
    lint:
        name: Check lint âš¡ï¸
        runs-on: ubuntu-latest
        container: node:lts
        steps:
            - name: Checkout ğŸš£
              uses: actions/checkout@v2
            - name: install packages ğŸ‘‡
              run: npm i
            - name: run lint âœ…âŒğŸ‘‰ğŸ‘ˆ
              run: npm run lint

    check-build:
        name: ğŸ³ Build React.js Frontend
        runs-on: ubuntu-latest
        timeout-minutes: 5
        container: node:lts
        steps:
          - name: ğŸ¤ Checkout
            uses: actions/checkout@v3
          
          - uses: pnpm/action-setup@v2
            with:
              version: 7

          - name: âŒš Compile React.js production build
            run: |
              pnpm i
              pnpm run build