name: CI

on:
    pull_request: 
        branches: 
            - "*"

jobs:
    lint:
        name: Check lint âš¡ï¸
        runs-on: ubuntu-latest
        container: node:lts
        steps:
            - name: Checkout ðŸš£
              uses: actions/checkout@v2
            - name: install packages ðŸ‘‡
              run: npm i
            - name: run lint âœ…âŒðŸ‘‰ðŸ‘ˆ
              run: npm run lint

    check-build:
        name: ðŸ³ Check Build 
        runs-on: ubuntu-latest
        timeout-minutes: 5
        container: node:lts
        steps:
          - name: ðŸŽ¤ Checkout
            uses: actions/checkout@v3

          - name: âŒš Compile production build
            run: |
              npm i
              npm run build
          - name: ðŸ¥º Finish leaw na
            run: echo -e "### Finish leaw na! \U0001F97A " >> $GITHUB_STEP_SUMMARY