name: CI

on:
    pull_request: 
        branches: 
            - "*"

jobs:
    lint:
        name: Check lint âš¡ï¸
        runs-on: ubuntu-latest
        container: node:lts
        steps:
            - name: Checkout ğŸš£
              uses: actions/checkout@v2
            - name: install packages ğŸ‘‡
              run: npm i
            - name: run lint âœ…âŒğŸ‘‰ğŸ‘ˆ
              run: npm run lint